### ISSUE TITLE
Reverse proxy support

### ISSUE THREAD

**Issue by cpecquerie** [ocombe/subNode#7]
Hi, 
It would be great to support reverse proxy.
Thanks,
Christophe.

**Comment by ocombe** [comment]
Hello !
I'm not sure I get it. What do you want subNode to do for reverse proxies ?
It's up to you to configure your proxy for access I think.

**Comment by cpecquerie** [comment]
Hi !
Yes, I use nginx to configure reverse proxy but some code in your application does not support it.
For example when I try to run subnode behing nginx as a reverse proxy, (with URL https://mydomain/subnode/), I get the following results (see screenshots)
Cheers,
Christophe.

![capture d ecran 2015-08-31 17 14 55](https://cloud.githubusercontent.com/assets/12511160/9582180/0959a2ba-5004-11e5-8afd-db14525fafba.png)

![capture d ecran 2015-08-31 17 14 02](https://cloud.githubusercontent.com/assets/12511160/9582189/1045bfdc-5004-11e5-9d8c-9f16ccec9291.png)

**Comment by ocombe** [comment]
I'm actually going to rewrite the entire app in angular 2 (just waiting for it to be more stable), so I won't be any update until then. I think that I'll start working on it in about 1 month.
I will also see if I can generate standalone apps as well using [electron](http://electron.atom.io/) :)

In your case it's probably the url of the translations that don't work, do you have any error in the console (saying that it's trying to load files with a 404 ?) ?

**Comment by ocombe** [comment]
It's on the roadmap for v2.0 (https://github.com/ocombe/subNode/issues/8)

**Comment by ocombe** [comment]
v2.0 is working with reverse proxies since this commit: https://github.com/ocombe/subNode/commit/d84c67bab9665815402bb4e094d0ed26ceac5cc5 :)
